### ISSUE TITLE
HeliumLogger enhancements

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Kitura#358]
- [x] Print only filename, not the full path
- [x] Be able to specify a custom format string for log output. 
    For example, if the user specifies log outputs as "%t - (%m)". It would print "04-12-2016 08:51 - (Message here)"
- [ ] Filter based on levels. 
    Such as only "info" and above would print all errors, warnings, and info. But would exclude verbose.

**Comment by rfdickerson** [comment]
Looks like we only have filtering based on logging-levels left.

**Comment by shmuelk** [comment]
The last item was handled by a PR.
